### ISSUE TITLE
implicitly discards parameters that have same base name but in other path hierarchy

### ISSUE THREAD

**Issue by aereal** [handlename/ssmwrap#50]
# expected behavior

We have these parameters in SSM parameter store:

- `/my/external-service-1/sercret-key`
- `/my/external-service-2/secret-key`

and run `ssmwrap -paths /my` then get these environment variables:

- `MY_EXTERNAL_SERVICE_1_SECRET_KEY`
- `MY_EXTERNAL_SERVCIE_2_SECRET_KEY`

# actual behavior

We only get `SECRET_KEY` that from `/my/external-service-2/secret-key` and have no way to get `/my/external-service-1/secret-key`.

This is caused by `formatParametersAsEnvVars` that uses only a last part of the path for environment variable name.
https://github.com/handlename/ssmwrap/blob/207423aa2f305109e96f355555a101bf4ae12d15/dest_env.go#L36-L46

# solution

We should use the entire path as environment variable name because parameter uniqueness is guaranteed by its entire path not only the last part of the path.

**Comment by handlename** [comment]
@aereal released as v1.2.0
https://github.com/handlename/ssmwrap/releases/tag/v1.2.0

Please use `-env-entire-path` option to enable feature.
Thank you for your contributing again!
